### PR TITLE
refactoring files strucutre

### PR DESCRIPTION
**Pull request by guilhermebodin**
Trying to make the extension for other cones more clear in the code

### CODE REVIEW

**Comment by guilhermebodin** [comment]
commit 0f43244 should solve [#34](https://github.com/mariohsouto/ProxSDP.jl/issues/34)

**Comment by joaquimg** [comment]
Nice to solve #34
Lets keep like this for this one.
But we should avoid making too many changes in PRs proposing a restructuring because potential bugs and slowliness are harder to track.

**Comment by guilhermebodin** [comment]
@joaquimg we can close this one and open new ones. One for the issue #34 and one for each new file of the reorganization. This will allow us to test it along the way

**Comment by joaquimg** [comment]
I think its ok to move files and add one else statement :)

**Pull request merged**
